language: java
jdk:
 - openjdk8
 
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - elena.alonsoporto@opendeusto.es
      - ander.eguiluz@opendeusto.es
      - borja.diazdeotazu@opendeusto.es
      - marcosbarcina@opendeusto.es
      
    on_success: never
    on_failure: always
