language: java
jdk:
 - openjdk12
services:
 - mysql
install: 
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
 - mvn clean compile
 - mvn datanucleus:schema-create 
 - mvn test
 
branches:
  only:
  - master

notifications:
  email:
    recipients:
      - elena.alonsoporto@opendeusto.es
      - ander.eguiluz@opendeusto.es
      - borja.diazdeotazu@opendeusto.es
      - marcosbarcina@opendeusto.es
      
    on_success: never
    on_failure: always
